//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.6
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. It should be kept private.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub b121a038-65ae-46f1-a772-9fc937042f74 aws-my-sample-app-android-v0.6";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
        Regions.US_EAST_1;
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:06fd2d11-07fe-4c90-8b80-8495dbf652c4";
    // Google Client ID for Web application
    public static final String GOOGLE_CLIENT_ID =
        "297847922195-q8flh2eq27uunicc2rq6ell9o5g2sv0v.apps.googleusercontent.com";
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "testsignon-userfiles-mobilehub-1118664329";
}
